Задание 2.4 NumPy Вектор и матрица

Примечание 1. Считать, что размерности вектора и матрицы соответствуют выполняемым операциям.
Примечание 2. Фраза умножение в обратном порядке означает, что умножение происходит по правилу: последний элемент строки на первый элемент вектора, …, первый элемент строки на последний элемент вектора.

5. Дан вектор 𝑥 и матрица 𝐴. Умножить все нечетные столбцы матрицы 𝐴 на вектор 𝑥. 
Результат записать в новую матрицу и разделить ее на максимальный элемент вектора 𝑥 (гарантируется, что это не ноль).

In [1]:
import numpy as np

In [8]:
import numpy as np

x = np.array([1, 2, 3, 4, 5]) 

A = np.array([
    [5, 0, 3, 3, 7],
    [7, 9, 3, 5, 2],
    [2, 4, 7, 6, 1],
    [8, 8, 1, 6, 0],
    [7, 7, 8, 1, 1]
])  

max_x = np.max(x)

# Определим индексы нечетных столбцов (индексация с нуля, поэтому 0, 2, 4 - это 1-й, 3-й, 5-й столбцы)
с = np.arange(0, A.shape[1], 2)

new_A = A.copy()
new_A[:, с] = A[:, с] * x[::-1][:, np.newaxis]
print("Матрица после умножения:\n", new_A)

result_matrix = new_A / max_x
print("Матрица после умножения и деления:\n", result_matrix)

Матрица после умножения:
 [[25  0 15  3 35]
 [28  9 12  5  8]
 [ 6  4 21  6  3]
 [16  8  2  6  0]
 [ 7  7  8  1  1]]
Матрица после умножения и деления:
 [[5.  0.  3.  0.6 7. ]
 [5.6 1.8 2.4 1.  1.6]
 [1.2 0.8 4.2 1.2 0.6]
 [3.2 1.6 0.4 1.2 0. ]
 [1.4 1.4 1.6 0.2 0.2]]
