Задание 2.3 NumPy Обработка матрицы

5. Выполнить обработку элементов прямоугольной матрицы 𝐴, имеющей 𝑛 строк и 𝑚 столбцов. Все элементы имеют целый тип. Дано целое число ℎ. Определить, какие столбцы имеют хотя бы одно такое число, а какие не имеют.

In [38]:
import numpy as np

In [57]:
n = 5  # количество строк
m = 4  # количество столбцов
h = 8  # заданное целое число

A = np.random.randint(0, 11, size=(n, m))

contains_h = np.any(A == h, axis=0)

columns_with_h = np.where(contains_h)[0]
columns_without_h = np.where(~contains_h)[0]
print("Матрица A:\n", A)
print("Столбцы, содержащие число {}: {}".format(h, columns_with_h))
print("Столбцы, не содержащие число {}: {}".format(h, columns_without_h))

Матрица A:
 [[8 1 5 8]
 [4 0 2 5]
 [5 0 8 1]
 [1 0 3 8]
 [8 4 4 0]]
Столбцы, содержащие число 8: [0 2 3]
Столбцы, не содержащие число 8: [1]
