Задание 2.2 NumPy Знакомство

Примечание. 
Пункты 2-8 каждого варианта связаны с матрицей, созданной в пункте 1. Пункты 9-10 используют свои собственные исходные данные.

5  вариант

1. Сгенерировать матрицу размером 2 × 8, заполненную целыми числами.

2. Вывести на экран элемент с индексами [1, 5].

3. Вывести на экран первую строку матрицы.

4. Вывести на экран четвертый столбец матрицы в обратном порядке.

5. Изменить форму матрицы с 2 × 8 на 4 × 4.

6. Вычесть из каждого элемента матрицы заданное число.

7. Найти минимум на главной диагонали матрицы.

8. Найти максимальный элемент в последнем столбце.

9. Дан одномерный массив. Определить процент положительных и отрицательных чисел.

10. В заданной матрице подсчитать среднее геометрическое двузначных чисел, расположенных в четных столбцах матрицы.

In [3]:
import numpy as np
import math

1. Сгенерировать матрицу размером 2 × 8, заполненную целыми числами.

In [17]:
matrix = np.random.randint(1, 100, size=(2, 8))
print(matrix)

[[58 48 82 54 72 47 16 25]
 [13 77  7 89 39 51 72 67]]


2. Вывести на экран элемент с индексами [1, 5].

In [18]:
elem = matrix[1, 5]
print(elem)

51


3. Вывести на экран первую строку матрицы.

In [19]:
first_row = matrix[0]
print(first_row)

[58 48 82 54 72 47 16 25]


4. Вывести на экран четвертый столбец матрицы в обратном порядке.

In [20]:
fourth_column_reversed = matrix[::-1, 3]
print(fourth_column_reversed)

[89 54]


5. Изменить форму матрицы с 2 × 8 на 4 × 4.

In [21]:
matrix_4x4 = matrix.reshape(4, 4)
print(matrix_4x4)

[[58 48 82 54]
 [72 47 16 25]
 [13 77  7 89]
 [39 51 72 67]]


6. Вычесть из каждого элемента матрицы заданное число.

In [37]:
number = 5
matrix = matrix_4x4 - number
print(matrix)

[[53 43 77 49]
 [67 42 11 20]
 [ 8 72  2 84]
 [34 46 67 62]]


7. Найти минимум на главной диагонали матрицы.

In [45]:
main_diag = np.diag(matrix_4x4)
min_diag = np.min(main_diag)
print(min_diag)

7


8. Найти максимальный элемент в последнем столбце.

In [26]:
last_column = matrix_4x4[:, -1]
max_last_column = np.max(last_column)
print(max_last_column)

89


9. Дан одномерный массив. Определить процент положительных и отрицательных чисел.

In [29]:
array = np.array([1, -3, 7, -8, 4, -2, 5, 2, -88, -27])
positive_count = np.sum(array > 0)
negative_count = np.sum(array < 0)
total_count = array.size
positive_percentage = (positive_count / total_count) * 100
negative_percentage = (negative_count / total_count) * 100
print(f"Положительные: {positive_percentage:.2f}%, Отрицательные: {negative_percentage:.2f}%")

Положительные: 50.00%, Отрицательные: 50.00%


In [28]:
array = np.array([1, -3, 7, -8, 4, -2, 5, 2, -88, -27,0])

positive_count = np.sum(array > 0)
negative_count = np.sum(array < 0)
zero_count = np.sum(array == 0)
total_count = array.size

positive_percentage = (positive_count / total_count) * 100
negative_percentage = (negative_count / total_count) * 100
zero_percentage = (zero_count / total_count) * 100

print(f"Положительные: {positive_percentage:.2f}%, Отрицательные: {negative_percentage:.2f}%, Нули: {zero_percentage:.2f}%")

Положительные: 45.45%, Отрицательные: 45.45%, Нули: 9.09%


10. В заданной матрице подсчитать среднее геометрическое двузначных чисел, расположенных в четных столбцах матрицы.

In [35]:
columns = matrix_4x4[:, ::2]
two_digit_numbers = columns[(np.abs(columns >= 10)) & (np.abs(columns < 100))]
geometric = np.exp(np.mean(np.log(two_digit_numbers))) if two_digit_numbers.size > 0 else float('nan')
print(geometric)

41.1560361589649
